# Generated by Django 4.2 on 2024-12-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_movement',
            field=models.IntegerField(default=0),
        ),
    ]
