# Generated by Django 4.2 on 2024-12-09 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_device_device_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='property_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
