# Generated by Django 5.0.2 on 2024-11-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_devicegeopoint_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegeopoint',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.device'),
        ),
        migrations.CreateModel(
            name='DeviceGeoPointworkingold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_movement', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.device')),
                ('geolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.projectgeolocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.project')),
            ],
        ),
    ]
