# Generated by Django 5.0.2 on 2024-11-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_devicegeopoint_device_devicegeopointworkingold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=100)),
                ('survey_number', models.CharField(max_length=100)),
                ('survey_sub_division', models.CharField(max_length=100)),
                ('patta_number', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('fmb', models.FileField(upload_to='fmb_pdfs')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.district')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.taluk')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.village')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('refference_name', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDeviceGeoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_movement', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.device')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.property')),
                ('geolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.propertygeolocation')),
            ],
        ),
    ]
