# Generated by Django 5.0.2 on 2024-11-05 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_property_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
