# Generated by Django 5.0.2 on 2024-11-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_device_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
