version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    volumes:
      - .:/app
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - DJANGO_DB_HOST=database
    depends_on:
      - database
    command: python manage.py runserver 0.0.0.0:8000

  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
     # - ./landshield.sql:/docker-entrypoint-initdb.d/landshield.sql  # Mount the SQL file for initialization
      - ./custom-my.cnf:/etc/mysql/conf.d/my.cnf  # Optional: Custom MySQL config
    command: --lower_case_table_names=1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
