version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - DJANGO_DB_HOST=database
    depends_on:
      - database

  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./custom-my.cnf:/etc/mysql/conf.d/my.cnf  # Mount custom MySQL config file
    command: --lower_case_table_names=1
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database  # Refers to the MySQL service name
      PMA_USER: myuser    # Your MySQL username
      PMA_PASSWORD: mypassword  # Your MySQL password
    ports:
      - "8080:80"
    networks:
    - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:

